apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnxpy2108-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnxpy2108-tenant-component
    app.kubernetes.io/part-of: loadnxpy2108-tenant-app
  name: loadnxpy2108-tenant-component
  namespace: loadnxpy2108-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnxpy2108-tenant-component
    weight: null
status: {}
